TraceStok/Controllers/ProductsController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ServiceContracts;
using ServiceContracts.DTO;

namespace TraceStok.Controllers
{
    [Route("[controller]")]
    public class ProductsController : Controller
    {
        private readonly IProductsService _productsService;

        public ProductsController(IProductsService productsService)
        {
            _productsService = productsService;
        }

        [Route("[action]/{SearchString}")]
        [Route("")]
        [Route("/")]
        public IActionResult Products(string? SearchString)
        {
            if (String.IsNullOrEmpty(SearchString))
            {
                List<ProductResponse> allProduccts = _productsService.GetAllProducts();

                return View(allProduccts);
            }

            List<ProductResponse> products = _productsService.GetAllProducts().Where(p => p.ProductName.Contains(SearchString)).ToList();

            return View(products);

        }

        [Route("[action]")]
        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }

        [Route("[action]")]
        [HttpPost]
        public IActionResult AddProduct(ProductAddReq productAddReq)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            ProductResponse productResponse = _productsService.AddProduct(productAddReq);

            return RedirectToAction("Products");
        }

        [Route("[action]")]
        [HttpGet]
        public IActionResult Delete(Guid? productID)
        {
            ProductResponse? productResponse = _productsService.GetProductByID(productID);
            if (productResponse == null)
            {
                return RedirectToAction("Products");
            }

            return View(productResponse);
        }

        [Route("[action]")]
        [HttpPost]
        public IActionResult Delete(Product product)
        {
            ProductResponse? productResponse = _productsService.GetProductByID(product.ProductID);
            if (productResponse == null)
            {
                return RedirectToAction("Products");
            }

            _productsService.DelProduct(product.ProductID);

            return RedirectToAction("Products");
        }

        [Route("[action]/{productID}")]
        [HttpGet]
        public IActionResult Update(Guid? productID) 
        {
            ProductResponse? productResponse = _productsService.GetProductByID(productID);
            if (productResponse == null)
            {
                return RedirectToAction("Products");
            }

            ProductUpdateReq productUpdateReq = productResponse.ToProductUpdateReq();

            return View(productUpdateReq);
        }

        [Route("[action]/{productID}")]
        [HttpPost]
        public IActionResult Update(ProductUpdateReq productUpdateReq)
        {
            ProductResponse? productResponse = _productsService.GetProductByID(productUpdateReq.ProductID);
            if (productResponse == null)
            {
                return RedirectToAction("Products");
            }

            if(!ModelState.IsValid) 
            {
                return View(productResponse.ToProductUpdateReq());
            }

            _productsService.UpdateProduct(productUpdateReq);

            return RedirectToAction("Products");
        }
    }
}

TraceStok/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace TraceStok.Controllers
{
    [Route("[controller]")]
    public class UsersController : Controller
    {
        private readonly IUsersService _usersService;

        public UsersController(IUsersService usersService)
        {
            _usersService = usersService;
        }

        [Route("/login")]
        public IActionResult LoginPage()
        {
            return View();
        }

        [Route("/register")]
        public IActionResult Register()
        {
            return View();
        }

        [Route("/usermanagment&{userID}")]
        public IActionResult UserManagment()
        {
            return View();
        }
    }
}

TraceStok/Views/Products/AddProduct.cshtml
@model ProductAddReq

@{
    ViewBag.Title = "TraceStok Product Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="blackBody">
    <div class="midCenter">
        <h1>Add Product</h1>
        <form asp-controller="Products" asp-action="AddProduct" method="post">
            <label asp-for="ProductName">Product Name:</label>
            <input asp-for="ProductName" />
            <br />
            <br />
            <label asp-for="ProductPrice">Product Price:</label>
            <input asp-for="ProductPrice" />
            <br />
            <br />
            <label asp-for="ProductQuantity">Quantity:</label>
            <input asp-for="ProductQuantity" />
            <br />
            <br />
            <button>Add Product</button>
        </form>
    </div>
</body>

TraceStok/Views/Products/Delete.cshtml
@model ProductResponse

@{
    ViewBag.Title = "TraceStok Delete Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="blackBody">
    <form asp-controller="Products" asp-action="Delete" method="post">
        <input type="hidden" asp-for="ProductID" />
        <h3>Are you sure? Delete @Model.ProductName?</h3>
        <button>Delete Product</button>
    </form>
</body>

TraceStok/Views/Products/Products.cshtml
@model IEnumerable<ProductResponse>
@using HtmlAgilityPack;

@{
    ViewBag.Title = "TraceStok Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="blackBody">
    <h1 class="topCenter">Products</h1>
    <br />
    <br />
    <form asp-controller="Products" asp-action="Search">
        <p>
            Product Name: <input type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
    <br />
    <br />
    <table id="table">
        <thead>
            <tr>
                <th style="font-size: 20px">Product ID </th>
                <th style="font-size: 20px">Product Name </th>
                <th style="font-size: 20px">Price </th>
                <th style="font-size: 20px">Quantity </th>
                <th style="font-size: 20px">Actions </th>
            </tr>
        </thead>
        <tbody>
            @foreach (ProductResponse product in Model)
            {
                <tr>
                    <td>@product.ProductID</td>
                    <td>@product.ProductName</td>
                    <td>@product.ProductPrice</td>
                    <td>@product.ProductQuantity</td>
                    <td>
                        <a asp-controller="Products" asp-action="Update" asp-route-ProductID="@product.ProductID" style="color: blue">Update</a> |
                        <a asp-controller="Products" asp-action="Delete" asp-route-ProductID="@product.ProductID" style="color: blue">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>

TraceStok/Views/Products/Update.cshtml
@model ProductUpdateReq

@{
    ViewBag.Title = "TraceStok Product Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="blackBody">
    <div class="midCenter">
        <h1>Product Update</h1>
        <form asp-controller="Products" asp-action="Update" method="post">
            <label asp-for="ProductName">Product Name:</label>
            <input asp-for="ProductName" />
            <br />
            <br />
            <label asp-for="ProductPrice">Product Price:</label>
            <input asp-for="ProductPrice" />
            <br />
            <br />
            <label asp-for="ProductQuantity">Quantity:</label>
            <input asp-for="ProductQuantity" />
            <br />
            <br />
            <button>Update Product</button>
        </form>
    </div>
</body>

TraceStok/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div>
        <div class="topnav">
            <h1 class="topCenter">TraceStok</h1>
            <div class="topCenter">
                <a asp-controller="Products" asp-action="Products" class="linkStyle">All Products</a>
                <a asp-controller="Products" asp-action="AddProduct" class="linkStyle">Add Product</a>
                <a asp-controller="Users" asp-action="LoginPage" class="linkStyle">Login</a>
                <a asp-controller="Users" asp-action="Register" class="linkStyle">Register</a>
            </div>
        </div>
        @RenderBody()
    </div>
</body>
</html>

TraceStok/Views/Users/LoginPage.cshtml
@model UserLoginReq

@{
    ViewBag.Title = "TraceStok Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>function alert() { alert("Under Construct!") }</script>

<body class="blackBody">
    <dialog open>
        <p>Under Construct</p>
        <form method="dialog">
            <button>OK</button>
        </form>
    </dialog>
    <div class="midCenter">
        <h1>Welcome, please login.</h1>
        <script>function alert() { alert("Under Construct!") }</script>
        <form asp-controller="Users" asp-action="login" method="post">
            <label asp-for="Email">E-mail:</label>
            <input asp-for="Email" type="email"/>
            <br/>
            <br/>
            <label asp-for="Password">Password:</label>
            <input asp-for="Password" type="password"/>
            <br/>
            <br/>
            <button style="align-items:flex-end">Login</button>
        </form>
        <p style="color: #FFFFFF">If you lost your crenditials please contact to manager.</p>
    </div>
</body>

TraceStok/Views/Users/Register.cshtml
@model UserAddReq

@{
    ViewBag.Title = "TraceStok Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="blackBody">
    <div class="midCenter">
        <h1 style="color: white">Register User</h1>
        <form asp-controller="Users" asp-action="Create" method="post">
            <label asp-for="Email">E-mail:</label>
            <input asp-for="Email" type="email"/>
            <br/>
            <br/>
            <label asp-for="Password">Password:</label>
            <input asp-for="Password" type="password"/>
            <br />
            <br />
            <label asp-for="PhoneNumber">Phone Number:</label>
            <input asp-for="PhoneNumber" type="number"/>
            <br />
            <br />
            <label asp-for="IsAdmin">Admin?:</label>
            <input asp-for="IsAdmin" type="checkbox"/>
            <br/>
            <br/>
            <button>Register User</button>
        </form>
    </div>
</body>